### ISSUE TITLE
python3.9: sip Unable to find file "QtCore/QtCoremod.sip" - possible workaround

### ISSUE THREAD

**Issue by lprobsth** [ros-melodic-arch/ros-melodic-python-qt-binding#5]
There are currently multiple issues in multiple repos open for this:
https://github.com/ros-noetic-arch/ros-noetic-python-qt-binding/issues/2
https://github.com/ros-melodic-arch/ros-melodic-rviz/issues/9
https://github.com/ros-visualization/python_qt_binding/issues/80
(yesterday I also found another one which I don't seem to find rn)

There is a patch file in both noetic and melodic arch repos which are as far as I now related to this issue - but installation still fails for me. All these issues mainly address python3.8 and I use python3.9. So maybe that's the reason why.

I wanted you to know that this workaround worked for me:

https://wiki.archlinux.org/index.php/ROS#Building_from_source

```bash
#mkdir -p /usr/share/sip
#this directory was already existing
sudo ln -s /usr/lib/python3.9/site-packages/PyQt5 /usr/share/sip/.
sudo ln -s /usr/lib/python3.9/site-packages/PyQt5/bindings/* /usr/share/sip/PyQt5/.
```

**Comment by bionade24** [comment]
Since this builds fine in our CI and is patched, I'll close this issue soon if you can't provide more information on why the matched maybe didn't work for you.
